
[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
dependencies = [
    "aiohttp>=3.13.5",
    "flask",
    "flask-cors",
    "flask-limiter",
    "logger>=1.4",
    "pycapnp",
    "requests>=2.33.1",
    "waitress",
]
requires-python = "==3.13.*"
name = "CVSE-frontend-main"
version = "0.1.0"
description = "CVSE 收录前端"
authors = [
    {name = "yhtq", email = "1414672068@qq.com"},
]
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false

[tool.pdm.scripts]
server = {call = "server:main"}
